package:
  name: radarmodel

source:
  git_url: https://github.com/ryanvolz/radarmodel.git

requirements:
  build:
    - python
    - setuptools
    - cython
    - numpy
  run:
    - python
    - setuptools
    - numba
    - numpy
    - pyfftw
    - scipy

test:
  imports:
    - radarmodel

about:
  home: http://github.com/ryanvolz/radarmodel
  license: BSD 3-Clause ("BSD New")
  summary: Mathematical radar models useful for inverting radar measurements
