package:
  name: radarmodel

source:
  path: ../
  #git_url: https://github.com/ryanvolz/radarmodel.git

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - rkl
    - numpy
    - pyfftw

test:
  imports:
    - radarmodel

about:
  home: http://github.com/ryanvolz/radarmodel
  license: MIT
  summary: Mathematical radar models useful for inverting radar measurements
